// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwBiFRVqJFYyuTCiR6cxWFNNyBJdK5jNY',
    appId: '1:303883149823:web:e339c433b119d4731487ca',
    messagingSenderId: '303883149823',
    projectId: 'rescuenow-7b085',
    authDomain: 'rescuenow-7b085.firebaseapp.com',
    storageBucket: 'rescuenow-7b085.appspot.com',
    measurementId: 'G-Z8R6MRVELE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfS7DFw_GCEwLHl1jDCDRU1TqyE1CYpH0',
    appId: '1:303883149823:android:beb045632b520e851487ca',
    messagingSenderId: '303883149823',
    projectId: 'rescuenow-7b085',
    storageBucket: 'rescuenow-7b085.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCov82T6_EI55h0qr9DDtQjSUyxlYFtwu4',
    appId: '1:303883149823:ios:b5b7d903ffe1ea5e1487ca',
    messagingSenderId: '303883149823',
    projectId: 'rescuenow-7b085',
    storageBucket: 'rescuenow-7b085.appspot.com',
    iosBundleId: 'com.example.rescueNowApp',
  );
}
