# Uniquely identifies your project in SonarQube (The key you made in Step 2)
sonar.projectKey=Flutter-ChatGPT

# The URL of your local SonarQube server
sonar.host.url=http://localhost:9000

# The token you generated in Step 2
sonar.login=sqp_70ab5c107496dee1edfe1656218f1b503531cc87

# Tells SonarQube where your Dart code is
sonar.sources=lib
sonar.tests=test

# Puts the working directory on your Mac's internal drive to bypass external drive limits
sonar.working.directory=/tmp/sonar_flutter_work

# Optional: If you want to exclude generated files from dragging down your score
sonar.exclusions=**/*.g.dart,**/*.freezed.dart